name = "LaskaStats"
uuid = "de767ba9-e829-4e7c-bf82-062dc00bf36c"
authors = ["Elias Sjölin", "<elias.sjolin@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
