name = "LaskaStats"
uuid = "de767ba9-e829-4e7c-bf82-062dc00bf36c"
authors = ["Elias Sjölin", "<elias.sjolin@gmail.com>"]
version = "0.0.2"

[deps]
LaskaCore = "9ad29ce2-7782-4744-ab48-6ef9cc0286bb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1"
Revise = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
